version: '3'

services:
  web:
    build: /./Users/ilia/PycharmProjects/testcaseLiis/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Users/ilia/PycharmProjects/testcaseLiis/:/dir
    ports:
      - 8008:8000
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - postgres_data:/Users/ilia/PostgresDb
    expose:
      - 5432
    environment:
      - POSTGRES_USER=ilia
      - POSTGRES_PASSWORD=hard
      - POSTGRES_DB=testliis


volumes:
  postgres_data:
